name: documentation
on:
    push:
        paths: ['examples/**', 'packages/**']
    branches:
        - main
permissions:
    contents: write
jobs:
    documentation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - name: Install
              run: |
                  npm install
                  npm run bootstrap
            - name: Build library
              run: |
                  npm run build-dev
            - name: Lint examples
              run: |
                  npm run lint-examples
            - name: Build examples
              run: |
                  npm run build-examples
            - name: Build storybook
              run: |
                  npm run build-storybook
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: storybook-static
                  clean: true
